url: https://y7kim.github.io
# works for local and gh-pages:
baseurl: /rose  
    
# remove baseurl - works for roseastrology.com


# Site settings
title: Kathy Rose Astrology
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 33588c
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url: https://www.facebook.com/kathy.rose.330
  - title: youtube-play
    url: http://youtube.com/roseastrology

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Prose.io settings
prose:
  rooturl: '_posts'
  siteurl: 'http://winber1.github.io/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "type"
        field:
          element: "hidden"
          value: "blog"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/articles:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "subtitle"
        field:
          element: "text"
          label: "Subtitle"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Eescriptio"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "Display Date"
          value: ""
      - name: "type"
        field:
          element: "hidden"
          value: "article"
      - name: "category"
        field:
          element: "text"
          label: "Category"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          value: ""
    _posts/homePage-videos:
      - name: "type"
        field:
          element: "hidden"
          value: "homePage"
      - name: "YouTubetag"
        field:
          element: "text"
          label: "You Tube tag"
          value: ""
